development:
  sessions:
    default:
      database: trunkit_development
      hosts:
        - dharma.mongohq.com:10051
      username: trunkit
      password: s.7!PVP5(BedGc

production:
  sessions:
    default:
      database: trunkit_production
      hosts:
        - dharma.mongohq.com:10052
      username: trunkit
      password: s.7!PVP5(BedGc
